<div class="popFase1 popJuegos olvContra">
  <h1>Contrase&ntilde;a</h1>
  <h3 style="margin-top: 35px;">&iquest;Olvidaste tu contrase&ntilde;a?</h3>
  <p>Ingresa tu email y te enviaremos un mail con una nueva contrase&ntilde;a para poder ingresar a tu cuenta.</p>
  <form id="formRPassword" name="formRPassword" method="post" action="">
  <div id="form-errors"><?php echo $this->message ?></div>
  <div style="width: 350px; text-align: center; margin: 12px auto 0; float: left;"><label id="label-email">E-mail:</label>
    <input name="email" type="text" class="required email" id="email" value="<?php echo $this->email ?>" />
  </div>
  <div class="clear"></div>
  <a href="#" class="btnNaranja100 bold center btnBig" id="submit">Enviar</a>
  </form>
</div>
