<?php
/*
if(strlen($this->content) > 0)
	echo $this->content;
else
	echo $this->form;
*/
?>

<div class="pop480 popStyle">
	<h1>Registro</h1>

    <h2>&iexcl;Bienvenido a El Profe Depor!</h2>
	<p>Divi&eacute;rtete jugando con los resultados del  Descentralizado y los puntajes de los jugadores. Piensa como t&eacute;cnico y suma  puntos fecha a fecha.</p>

<form id="formRegistro" name="formRegistro" method="post" action="">
      <input name="tipodoc_id" type="hidden" id="tipodoc_id" value="1" />
      <input name="ubigeo_id" type="hidden" id="ubigeo_id" value="000000" />
      <table border="0" cellspacing="0" cellpadding="0" class="formulaDepor">
        <tr>
          <td valign="middle"><div class="dataSingle" id="label-name">Nombre:</div></td>
          <td><input name="name" type="text" class="required" id="name" maxlength="30" /></td>
        </tr>
        <tr>
          <td><div class="dataSingle" id="label-last_name">Apellidos:</div></td>
          <td><input name="last_name" type="text" id="last_name" class="required" /></td>
        </tr>
        <tr>
          <td><div class="dataSingle" id="label-email">E-mail:</div></td>
          <td><input name="email" type="text" id="email" class="required email" /></td>
        </tr>
        <tr>
          <td><div class="dataDoble" id="label-confirm_email">Confirmar<br />e-mail:</div></td>
          <td><input name="confirm_email" type="text" id="confirm_email" /></td>
        </tr>
        <tr>
          <td><div class="dataSingle" id="label-password">Contrase&ntilde;a:</div></td>
          <td><input name="password" type="password" id="password" /></td>
        </tr>
        <tr>
          <td><div class="dataDoble" id="label-confirm_password">Confirmar<br />contrase&ntilde;a:</div></td>
          <td><input name="confirm_password" type="password" id="confirm_password" /></td>
        </tr>
      </table>
      <div id="form-errors"></div>
  	  <a href="#" id="submit" class="btnNaranja180 bold center btnBig">Unirme a El Profe Depor</a>
  </form>
<div class="msjBottomRegistro">

	    <p>Al hacer clic en ‘Unirme a El Profe Depor’, confirmas que aceptas los <a href="#">t&eacute;rminos y condiciones.</a></p>
  </div>
<!--fin popRegistro-->
</div>
