<div style="background: #33FFFF">
  <div id="form-errors"><?php echo $this->message ?></div>
  <form id="formRPassword" name="formRPassword" method="post" action="">
    <table border="1" cellpadding="0" cellspacing="0">
      <tr>
        <td>Ingrese Email:</td>
        <td><label>
          <input name="email" type="text" class="required email" id="email" value="<?php echo $this->email ?>" />
        </label></td>
      </tr>
      <tr align="center">
        <td colspan="2"><label>
          <input type="submit" value="Enviar" />
        </label></td>
      </tr>
    </table>
  </form>
</div>
