<div class="resRight">
  <div class="encuenttro">
    <div class="equipo"><img src="<?php echo $this->Image('_logo_juanAurich.png') ?>" />
        <p>jUAN aURICH</p>
    </div>
    <div class="versus"></div>
    <div class="equipo"><img src="<?php echo $this->Image('_logo_cni.png') ?>" />
        <p>C.N.I</p>
    </div>
  </div>
  <!--fin encuentro-->
  <div class="overResulEncuentro">
    <div class="resulLeft">
      <ul>
        <li class="top">01</li>
        <li>
          <div class="jugador">12 Libman</div>
          <div class="puntaje">5</div>
          <div class="clear"></div>
        </li>
        <li>
          <div class="jugador">12 Libman</div>
          <div class="puntaje">5</div>
          <div class="clear"></div>
        </li>
        <li>
          <div class="jugador">12 Libman</div>
          <div class="puntaje">5</div>
          <div class="clear"></div>
        </li>
        <li>
          <div class="jugador">12 Libman</div>
          <div class="puntaje">5</div>
          <div class="clear"></div>
        </li>
        <li>
          <div class="jugador">12 Libman</div>
          <div class="puntaje">5</div>
          <div class="clear"></div>
        </li>
        <li>
          <div class="jugador">12 Libman</div>
          <div class="puntaje">5</div>
          <div class="clear"></div>
        </li>
        <li>
          <div class="jugador">12 Libman</div>
          <div class="puntaje">5</div>
          <div class="clear"></div>
        </li>
        <li>
          <div class="jugador">12 Libman</div>
          <div class="puntaje">5</div>
          <div class="clear"></div>
        </li>
        <li>
          <div class="jugador">12 Libman</div>
          <div class="puntaje">5</div>
          <div class="clear"></div>
        </li>
        <li>
          <div class="jugador">12 Libman</div>
          <div class="puntaje">5</div>
          <div class="clear"></div>
        </li>
        <li>
          <div class="jugador">12 Libman</div>
          <div class="puntaje">5</div>
          <div class="clear"></div>
        </li>
        <li>
          <div class="jugador">12 Libman</div>
          <div class="puntaje">5</div>
          <div class="clear"></div>
        </li>
        <li class="marcador">Puntaje:
          <div>4.5</div>
        </li>
        <li>DT: Fulanito de tal</li>
      </ul>
    </div>
    <!--fin resulLeft-->
    <div class="resulRight">
      <ul>
        <li class="top">02</li>
        <li>
          <div class="jugador">12 Libman</div>
          <div class="puntaje">5</div>
          <div class="clear"></div>
        </li>
        <li>
          <div class="jugador">12 Libman</div>
          <div class="puntaje">5</div>
          <div class="clear"></div>
        </li>
        <li>
          <div class="jugador">12 Libman</div>
          <div class="puntaje">5</div>
          <div class="clear"></div>
        </li>
        <li>
          <div class="jugador">12 Libman</div>
          <div class="puntaje">5</div>
          <div class="clear"></div>
        </li>
        <li>
          <div class="jugador">12 Libman</div>
          <div class="puntaje">5</div>
          <div class="clear"></div>
        </li>
        <li>
          <div class="jugador">12 Libman</div>
          <div class="puntaje">5</div>
          <div class="clear"></div>
        </li>
        <li>
          <div class="jugador">12 Libman</div>
          <div class="puntaje">5</div>
          <div class="clear"></div>
        </li>
        <li>
          <div class="jugador">12 Libman</div>
          <div class="puntaje">5</div>
          <div class="clear"></div>
        </li>
        <li>
          <div class="jugador">12 Libman</div>
          <div class="puntaje">5</div>
          <div class="clear"></div>
        </li>
        <li>
          <div class="jugador">12 Libman</div>
          <div class="puntaje">5</div>
          <div class="clear"></div>
        </li>
        <li>
          <div class="jugador">12 Libman</div>
          <div class="puntaje">5</div>
          <div class="clear"></div>
        </li>
        <li>
          <div class="jugador">12 Libman</div>
          <div class="puntaje">5</div>
          <div class="clear"></div>
        </li>
        <li class="marcador">Puntaje:
          <div>4.5</div>
        </li>
        <li>DT: Fulanito de tal</li>
      </ul>
    </div>
    <!--fin resulRight-->
    <p><span class="bold">Goles:</span> Quinteros(12&rsquo;), Ramos(45&rsquo;), Castillo(58&rsquo;) hhnana hahnaa ajaga ha l aja 
      mhghhjaoiqjq ,na ajkhga <span class="bold">Tarjetas amarillas:</span> a  gv  afgb </p>
  </div>
  <!--fin overResulEncuentro-->
</div>
