<form id="" name="" method="post" action="<?php echo $this->baseUrl();?>/index/add">
  <table width="200" border="1" align="center" cellpadding="1" cellspacing="1">
    <tr>
      <td colspan="2" align="center"><?php echo $this->titleForm ?>
      <input name="eq_id" type="hidden" id="eq_id" value="<?php print_r($this->equipo->eq_id) ?>" /></td>
    </tr>
    <tr>
      <td>Nombre</td>
      <td><label>
        <input type="text" name="nombre" id="nombre" value="<?php print_r($this->equipo->nombre) ?>" />
      </label></td>
    </tr>
    <tr>
      <td colspan="2" align="center"><label>
        <input type="submit" value="Guardar" />
      </label></td>
    </tr>
  </table>
</form>
