<center>
<table width="580" border="0" align="center" cellpadding="0" cellspacing="0" style="line-height:0; background: #f9f9f9; text-align:left;">
      <tr>
        <td><img src="<?php echo $this->host;?>/images/head.jpg" width="580" height="186" /></td>
      </tr>
      <tr>
        <td style="padding:0 20px;">
        <h1 style="font-family:Verdana, Geneva, sans-serif; font-size: 18px; margin:0; padding:0; font-weight:bold; color:#537700; line-height: 38px;">
        Hola <?php echo $this->admin;?></h1>

        <p style="font-family:Verdana, Geneva, sans-serif; font-size: 12px; margin:0; padding:0; color:#555555; line-height:16px;">
             El usuario <strong><?php echo $this->nombre_persona;?></strong> quiere unirse a tu mancha <strong><?php echo $this->nombre_grupo;?></strong>. <br/>
		     Para aceptarlo haz click en el siguiente enlace.
		</p>

             <a style="font-family:Verdana, Geneva, sans-serif; font-size: 12px; margin:0 0 40px 15px; padding:0; color:#555555; line-height: 28px;" href="<?php echo $this->host;?>">http://www.elprofedepor.pe</a>

        </td>
      </tr>
      <tr>
        <td height="20">&nbsp;</td>
      </tr>
      <tr>
        <td>
        <div style="float: left;">
       	  <img src="<?php echo $this->host;?>/images/foot.jpg" />
        </div>
        <div style="float:right; margin: 13px 40px 0 0;">
        	<p style="font-family:Verdana, Geneva, sans-serif; font-size: 11px; margin:0 0 0 15px; padding:0; color:#555555; line-height: 28px;">
            Todos los derechos reservados Depor 2011</p>
        </div>
        </td>
      </tr>
      <tr>
        <td height="20">&nbsp;</td>
      </tr>
    </table>
</center>