<center>
  <table width="580" border="0" align="center" cellpadding="0" cellspacing="0" style="line-height:0; background: #f9f9f9; text-align:left;">
    <tr>
      <td><img src="<?php echo $this->host ?>/images/head.jpg" width="580" height="186" /></td>
    </tr>
    <tr>
      <td style="padding:0 20px;"><h1 style="font-family:Verdana, Geneva, sans-serif; font-size: 18px; margin:0; padding:0; font-weight:bold; color:#537700; line-height: 38px;"> Hola <?php echo $this->jugador ?></h1>
          <p style="font-family:Verdana, Geneva, sans-serif; font-size: 12px; margin:0 0 10px 0; padding:0; color:#555555; line-height:16px;"> Tu amigo(a) <strong><?php echo $this->amigo ?></strong> te invita a jugar <strong>El Profe Depor</strong><br />
            &iexcl;Participa y demuestra cu&aacute;nto sabes de f&uacute;tbol!</p>
        <p style="font-family:Verdana, Geneva, sans-serif; font-size: 12px; margin:0 0 0 15px; padding:0; color:#555555; line-height: 18px;">&nbsp;</p>
        <center>
            <a style="font-family:Verdana, Geneva, sans-serif; font-size: 12px; margin:0 auto;padding:8px 15px; color:#555555; line-height: 28px; 
        background: #acce39; text-decoration: none; font-weight: bold; color: #000;" href="<?php echo $this->link ?>" target="_blank"> Ingresa aqu&iacute; </a>
        </center></td>
    </tr>
    <tr>
      <td height="20">&nbsp;</td>
    </tr>
    <tr>
      <td><div style="float: left;"> <img src="<?php echo $this->host ?>/images/foot.jpg" /> </div>
          <div style="float:right; margin: 13px 40px 0 0;">
            <p style="font-family:Verdana, Geneva, sans-serif; font-size: 11px; margin:0 0 0 15px; padding:0; color:#555555; line-height: 28px;"> Todos los derechos reservados Depor 2011</p>
          </div></td>
    </tr>
    <tr>
      <td height="20">&nbsp;</td>
    </tr>
  </table>
</center>
