<center>
  <table width="580" border="0" align="center" cellpadding="0" cellspacing="0" style="line-height:0; background: #f9f9f9; text-align:left;">
    <tr>
      <td><img src="http://<?php echo $this->host ?>/images/head.jpg" width="580" height="186" /></td>
    </tr>
    <tr>
      <td style="padding:0 20px;"><h1 style="font-family:Verdana, Geneva, sans-serif; font-size: 18px; margin:0; padding:0; font-weight:bold; color:#537700; line-height: 38px;"> BIENVENIDOS A EL PROFE DEPOR</h1>
          <h2 style="font-family:Verdana, Geneva, sans-serif; font-size: 14px; margin:0; padding:0; font-weight:bold; color:#555555; line-height: 28px;"> DEMUESTRA CUANTO SABES DE F&Uacute;TBOL</h2>
        <p style="font-family:Verdana, Geneva, sans-serif; font-size: 12px; margin:0; padding:0; color:#555555; line-height:16px;"> Divi&eacute;rtete jugando con los resultados del Descentralizado y los puntajes de
          los jugadores. Piensa como t&eacute;cnico fecha a fecha y empieza a sumar puntos.</p>
        <h1 style="font-family:Verdana, Geneva, sans-serif; font-size: 12px; margin:0; padding:0; font-weight:bold; color:#537700; line-height: 38px;"> &gt; TUS DATOS REGISTRADOS SON:</h1>
        <p style="font-family:Verdana, Geneva, sans-serif; font-size: 12px; margin:0 0 0 15px; padding:0; color:#555555; line-height: 18px;"> <strong>Usuario:</strong> <?php echo $this->jugador['email'] ?></p>
        <p style="font-family:Verdana, Geneva, sans-serif; font-size: 12px; margin:0 0 0 15px; padding:0; color:#555555; line-height: 18px;"> <strong>Clave:</strong> <?php echo $this->jugador['password'] ?></p>
        <h1 style="font-family:Verdana, Geneva, sans-serif; font-size: 12px; margin:0; padding:0; font-weight:bold; color:#537700; line-height: 38px;">
        &gt; INGRESA A TU PRIMERA SESI&Oacute;N DANDO CLIC A LA SIGUIENTE DIRECCI&Oacute;N:
        </h1>
         <p style="font-family:Verdana, Geneva, sans-serif; font-size: 12px; margin:0 0 0 15px; padding:0; color:#555555; line-height: 18px;"><a style="font-family:Verdana, Geneva, sans-serif; font-size: 12px; margin:0 0 0 15px; padding:0; color:#555555; line-height: 28px;" href="<?php echo $this->link ?>"><?php echo $this->link ?></a></p>
         <h1 style="font-family:Verdana, Geneva, sans-serif; font-size: 12px; margin:0; padding:0; font-weight:bold; color:#537700; line-height: 28px;">
        &gt; CREA UNA MANCHA:
        </h1>
         <p style="font-family:Verdana, Geneva, sans-serif; font-size: 12px; margin:0 0 0 15px; padding:0; color:#555555; line-height: 28px;"> Crea tu mancha para compartir informaci&oacute;n y competir por el mayor puntaje.</p></td>
    </tr>
    <tr>
      <td height="20">&nbsp;</td>
    </tr>
    <tr>
      <td><div style="float: left;"> <img src="http://<?php echo $this->host ?>/images/foot.jpg" /> </div>
          <div style="float:right; margin: 13px 40px 0 0;">
            <p style="font-family:Verdana, Geneva, sans-serif; font-size: 11px; margin:0 0 0 15px; padding:0; color:#555555; line-height: 28px;"> Todos los derechos reservados Depor 2011</p>
          </div></td>
    </tr>
    <tr>
      <td height="20">&nbsp;</td>
    </tr>
  </table>
</center>