<center>
  <table width="580" border="0" align="center" cellpadding="0" cellspacing="0" style="line-height:0; background: #f9f9f9; text-align:left;">
    <tr>
      <td><img src="http://<?php echo $this->host ?>/images/head.jpg" width="580" height="186" /></td>
    </tr>
    <tr>
      <td style="padding:0 20px;"><h1 style="font-family:Verdana, Geneva, sans-serif; font-size: 18px; margin:0; padding:0; font-weight:bold; color:#537700; line-height: 38px;"> Hola <?php echo $this->nombres ?></h1>
          <p style="font-family:Verdana, Geneva, sans-serif; font-size: 12px; margin:0 0 10px 0; padding:0; color:#555555; line-height:16px;"> Te enviamos una nueva contrase&ntilde;a &iexcl;Para que puedas seguir participando!</p>
        <p style="font-family:Verdana, Geneva, sans-serif; font-size: 12px; margin:0 0 0 15px; padding:0; color:#555555; line-height: 18px;"> <strong>Usuario:</strong> <?php echo $this->email ?></p>
        <p style="font-family:Verdana, Geneva, sans-serif; font-size: 12px; margin:0 0 0 15px; padding:0; color:#555555; line-height: 18px;"> <strong>Clave:</strong> <?php echo $this->password ?></p>
        <p style="font-family:Verdana, Geneva, sans-serif; font-size: 12px; margin:10px 0; padding:0; color:#555555; line-height:16px;"> Entra al siguiente link e ingresa la nueva contrase&ntilde;a para poder entrar a tu cuenta.</p>
        <p style="font-family:Verdana, Geneva, sans-serif; font-size: 12px; margin:10px 0; padding:0; color:#555555; line-height:16px;">
        <a style="font-family:Verdana, Geneva, sans-serif; font-size: 12px; margin:0 0 0 15px; padding:0; color:#555555; line-height: 28px;" href="<?php echo $this->link ?>"><?php echo $this->link ?></a>
        </p></td>
    </tr>
    <tr>
      <td height="20">&nbsp;</td>
    </tr>
    <tr>
      <td><div style="float: left;"> <img src="http://<?php echo $this->host ?>/images/foot.jpg" /> </div>
          <div style="float:right; margin: 13px 40px 0 0;">
            <p style="font-family:Verdana, Geneva, sans-serif; font-size: 11px; margin:0 0 0 15px; padding:0; color:#555555; line-height: 28px;"> Todos los derechos reservados Depor 2011</p>
          </div></td>
    </tr>
    <tr>
      <td height="20">&nbsp;</td>
    </tr>
  </table>
</center>