  <div class="contAyuda">
    <h4>Ayuda</h4>
    <div class="ayuda">
      <div class="left">
        <ul>
          <li><a href="#uno">&iquest;Qu&eacute; es el profe Depor?</a></li>
          <li><a href="#dos">&iquest;C&oacute;mo ingresar?</a></li>
          <li><a href="#tre">&iquest;C&oacute;mo empiezo a jugar?</a></li>
          <li><a href="#cua">&iquest;C&oacute;mo gano puntos?</a></li>
          <li><a href="#cin">&iquest;Qu&eacute; es una mancha?</a></li>
          <li><a href="#sei">&iquest;C&oacute;mo creo una mancha?</a></li>
          <li><a href="#sie">&iquest;Qu&eacute; es un ranking?</a></li>
        </ul>
      </div>
      <!--fin ayudaLeft-->
      <div class="right">
        <div class="overAyuda"> <a name="uno" id="uno"></a>
            <h1>&iquest;Qu&eacute; es el profe Depor?</h1>
          <p>&ldquo;El  Profe Depor&rdquo; es el juego web donde podr&aacute;s demostrar cuanto sabes de futbol, fecha  tras fecha te divertir&aacute;s jugando con los resultados del campeonato  descentralizado y los puntajes de los jugadores. Piensa como t&eacute;cnico fecha a  fecha &iexcl;y empieza a sumar puntos!</p>
        <a name="dos" id="dos"></a>
            <h1>&iquest;C&oacute;mo ingresar?</h1>
          <p>Puedes  ingresar registr&aacute;ndote directamente desde la p&aacute;gina de &ldquo;El Profe Depor&rdquo;  llenando el formulario con tus datos o desde una cuenta en Twiter, Facebook o  Gmail.<strong></strong></p>
        <a name="tre" id="tre"></a>
            <h1>&iquest;C&oacute;mo empiezo a jugar?</h1>
          <p>Luego  de haber iniciado sesi&oacute;n desde tu cuenta, haz click sobre la pesta&ntilde;a &ldquo;JUEGA&rdquo;  que te llevar&aacute; a la secci&oacute;n donde aparecer&aacute; una lista con todos partidos del  descentralizado que se jugar&aacute;n durante la semana. Para jugar s&oacute;lo tienes que  elegir las opciones que aparecer&aacute;n&nbsp; en  los cuadros. El juego estar&aacute; divido en 3 niveles; &ldquo;Nivel 1&rdquo;, &ldquo;Nivel 2&rdquo; y &ldquo;Nivel  3&rdquo;. No todos los quipos estar&aacute;n en todos los niveles.</p>
        <a name="cua" id="cua"></a>
            <h1>&iquest;C&oacute;mo gano puntos?</h1>
          <p>En  cada uno de los niveles tendr&aacute;s la opci&oacute;n de elegir los resultados de los  partidos del Campeonato Descentralizado, por ejemplo:</p>
          <p><u>Nivel  1</u><br />
            En  cada uno de los casilleros podr&aacute;s marcar los resultandos de cada partido con  las siguientes opciones &ldquo;Gana Local&rdquo;, &ldquo;Empata&rdquo;, &ldquo;Gana Visita&rdquo;, cada opci&oacute;n  equivale a 60, 50 y 70 puntos respectivamente. Luego de elegir las opciones haz  click en el bot&oacute;n &ldquo;JUGAR&rdquo; que est&aacute; en la parte inferior de esta secci&oacute;n y  autom&aacute;ticamente aparecer&aacute; una ventana invit&aacute;ndote a sumar m&aacute;s puntos jugando el  siguiente nivel.</p>
          <p><u>Nivel  2</u><br />
            En  este nivel podr&aacute;s predecir el n&uacute;mero de goles que tendr&aacute;n los resultados que  haz marcado en el Nivel 1, es decir, podr&aacute;s marcar los casilleros con las  opciones &ldquo;Por m&aacute;s de 1 gol&rdquo;, &ldquo;Sin goles&rdquo;, &ldquo;Por un gol&rdquo;, &ldquo;Por 1 gol o m&aacute;s&rdquo;, cada  opci&oacute;n equivale a 35, 20, 20 y 35 puntos respectivamente. Luego haz click en el  bot&oacute;n &ldquo;JUGAR&rdquo; que est&aacute; en la parte inferior de esta secci&oacute;n, de inmediato  aparecer&aacute; una invitaci&oacute;n&nbsp; que te llevar&aacute;  al Nivel 3.</p>
          <p><u>Nivel  3</u><br />
          Aqu&iacute; podr&aacute;s calificar  el rendimiento de tu equipo favorito, haciendo click sobre el equipo de tu  preferencia, aparecer&aacute; una ventana donde podr&aacute;s calificar a tu equipo de  acuerdo a su rendimiento en los diferentes aspectos deportivos como &ldquo;Ataque&rdquo;, &ldquo;Defensa&rdquo;,  &ldquo;Fair Play&rdquo;, &ldquo;Depor&rdquo; cada opci&oacute;n tendr&aacute; diferentes campos como &ldquo;Monse&rdquo;, &ldquo;Cumplidor&rdquo;  y &ldquo;Letal&rdquo;, todos con puntajes diferentes.</p>
          <a name="cin" id="cin"></a>
          <h1>&iquest;Qu&eacute; es una mancha?</h1>
          <p>Una  &ldquo;Mancha&rdquo; es una red de &ldquo;Contactos&rdquo; o &ldquo;Patas&rdquo; a la cual los usuarios tendr&aacute;n la  oportunidad de unirse&rdquo;. Pertenecer a una mancha te permitir&aacute; ver el ranking por  mancha, por fecha y general.</p>
        <a name="sei" id="sei"></a>
            <h1>&iquest;C&oacute;mo creo una mancha?</h1>
          <p>Haz  click sobre la pesta&ntilde;a &ldquo;MI MANCHA&rdquo; y aparecer&aacute; un formulario donde podr&aacute;s  completar las opciones y crear tu mancha, al crear una mancha te conviertes autom&aacute;ticamente  en el administrador de ella. En el lado izquierdo de esta secci&oacute;n encontrar&aacute;s  las opciones &ldquo;Crea una mancha&rdquo; y &ldquo;&Uacute;nete a una mancha&rdquo;. <br />
Si  deseas que tu mancha sea privada marca la opci&oacute;n &ldquo;Sobrada&rdquo; y quieres que est&eacute;  abierta para el p&uacute;blico en general marca la opci&oacute;n &ldquo;Brava&rdquo;.</p>
        <a name="sie" id="sie"></a>
            <h1>&iquest;Qu&eacute; es un ranking?</h1>
          <p>Es  la lista en donde se actualizar&aacute;n los puntajes de cada &ldquo;Usuario&rdquo;. De esta  manera el usuario podr&aacute; analizar su puntaje y compararlo semana a semana de  acuerdo a sus aciertos. Aqu&iacute; podr&aacute;s ver el ranking general de &ldquo;El Profe Depor&rdquo;,  el ranking de tu mancha y el ranking de tu mancha por fecha.</p>
        </div>
        <!--fin overAyuda-->
      </div>
      <!--fin ayudaRight-->
      <div class="clear"></div>
    </div>
    <!--fin ayuda-->
  </div>
</div>
<!--fin wrapper-->