<div class="popAyudaPoliticasMapa popStyle">
  <h4>Mapa del sitio</h4>
  <div class="ayuda">
    <ol class="sitemap">
      <li><a href="/portada/">Portada</a></li>
      <li><a href="/juego/fase1/">Juego</a></li>
      <li><a href="/grupo/">Mi Mancha</a></li>
      <li><a href="/ranking/">Rankings</a></li>
      <li><a href="/juego/">Fixture y Mis Jugadas</a></li>
      <li><a href="/resultado/">Los Resultados</a></li>
      <li><a href="javascript:;" id="lnkEditarPerfil">Editar Perfil</a></li>
      <li><a href="/articulo/index/id/1">Noticias Depor</a></li>
      <li><a href="/articulo/index/id/2">El Profe Depor</a></li>
      <li><a href="/articulo/index/id/3">El Cuy Yimy</a></li>
      <li><a href="javascript:;" id="lnkAyuda">Ayuda</a></li>
      <li><a href="javascript:;" id="lnkPolitica">Pol&iacute;ticas del Sitio</a></li>
    </ol>
    <!--fin sitemap-->
    <div class="clear"></div>
  </div>
  <!--fin ayuda-->
</div>