<div class="popBienvenido popStyle">
	<h4>Aprende a jugar</h4>
    <h5>1</h5>
    <p>Aqu&iacute; encontrar&aacute;s todo lo  que necesitas saber para jugar El Profe Depor. Aprende a usar tus conocimientos  futboleros para sumar puntos. Aprende tambi&eacute;n a crear una mancha para  enfrentarte a tus patas. &iquest;Qu&eacute; es un ranking? &iquest;C&oacute;mo veo los resultados? Es  facil&iacute;simo, aqu&iacute; respondemos a todas tus preguntas.</p>

<a href="/ayuda/" target="_blank" class="btnNaranja180 bold center btnBig">Lee las instrucciones</a>

    <a href="javascript:;" id="next" class="btnSaltar">[Saltar instrucciones]</a>
<!--fin popRegistro-->
</div>