<div class="popBienvenido popStyle">
	<h4>Crea tu mancha</h4>
    <h5>2</h5>
    <p>Aqu&iacute; puedes armar un  grupo para enfrentarte a la gente que t&uacute; quieras: tus amigos del colegio, de la  universidad, del barrio, de la oficina, etc&eacute;tera. T&uacute; decides qu&eacute; grupo crear y  te conviertes en el administrador. Tambi&eacute;n puedes buscar y elegir una mancha  que ya existe y a la que quieres pertenecer. El ranking de manchas aparece  fecha a fecha.</p>

<a href="/grupo/ver/id/1" class="btnNaranja180 bold center btnBig">Crea una mancha o busca una</a>
    
    <a href="/juego/" class="btnSaltar">[Ingresa al juego]</a>
<!--fin popRegistro-->
</div>