<div class="pop296 popStyle">
  <h1>Recomendar</h1>
  <form id="formShare" name="formShare" method="post" action="">
    <div id="form-errors"></div>
    <p class="bold">Recomienda El Profe Depor a tus amigos:</p>
    <div class="popRecomendar">
      <table width="350" border="1" class="formulaDepor">
        <tr>
          <td><div class="dataSingle" id="label-my_name">Tu nombre:</div></td>
          <td width="25">&nbsp;</td>
          <td><div class="dataSingle" id="label-my_email">Tu e-mail:</div></td>
        </tr>
        <tr>
          <td><input name="my_name" type="text" id="my_name" /></td>
          <td width="25">&nbsp;</td>
          <td><input name="my_email" type="text" id="my_email" /></td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td width="25">&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td><div class="dataSingle" id="label-his_name">Nombre de tu amigo:</div></td>
          <td width="25">&nbsp;</td>
          <td><div class="dataSingle" id="label-his_email">E-mail de tu amigo:</div></td>
        </tr>
        <tr>
          <td><input name="his_name" type="text" id="his_name" /></td>
          <td width="25">&nbsp;</td>
          <td><input name="his_email" type="text" id="his_email" /></td>
        </tr>
      </table>
    </div>
    <!--fin popRecomendar-->
    <a href="javascript:;" id="submit" class="btnNaranja180 bold center btnBig">Recomendar</a>
    <!--fin popRegistro-->
    </form>
</div>
