<form id="formTwitter" name="formTwitter" method="post">
 <div class="pop438 popStyle">
	<h1>Registro</h1>

    <h3>Tu cuenta ha sido vinculada a Twitter</h3>
    <p style="text-align:center;">Ingresa tu <label id="label-email">email</label> para completar el registro.</p>
    <div id="form-errors"></div>
    <p style="text-align:center; margin: 15px 0;">
      <input name="email" type="text" id="email" style="text-align:center;" size="40" />
	</p>
	<a href="javascript:;" id="submit" class="btnNaranja100 bold center btnBig">Enviar</a>
<!--fin popRegistro-->
</div>
</form>

