Fecha:<?php echo $this->fechas['descripcion'];?><br>
Intervalo: <?php echo $this->fechas['intervalo'];?>
<form name="frmResultadoPartido" id="frmResultadoPartido" method="post">
 <input type="hidden" name="fecha_id" id="fecha_id" value="<?php echo $this->fechas['fecha_id'];?>">
<div class="containertable">
<table border="1" width="90%" cellspacing="3" align="center">
          <tr class="list1">
               <td>ID</td>
               <td>LOCAL</td>
               <td></td>
               <td>VISITANTE</td>
               <td>GOLES LOCAL</td>
               <td>GOLES VISITANTE</td>
          </tr>
          <?php
          foreach($this->partidos as $indice => $value){
          if(count($value->resultados)>0){
               $resultados      = $value->resultados;
               $clave_id1        = $resultados['clave_id1'];
               $clave_id2        = $resultados['clave_id2'];
               $resultado_id = $resultados['resultado_id'];
               $goles_local   =  $resultados['goles_local'];
               $goles_visita =  $resultados['goles_visita'];
          }
          else{
               $clave_id1  = "";
               $clave_id2  = "";
               $resultado_id = "";
               $goles_local    = "";
               $goles_visita  = "";
          }
          ?>
          <tr class="list_a">
               <td>
                    <input type="hidden" name="resultado_id[<?php echo $indice;?>]"  id="resultado_id[<?php echo $indice;?>]" value="<?php echo  $resultado_id;?>"  size="2"/>
                    <input type="hidden" name="partido_id[<?php echo $indice;?>]"  id="partido_id[<?php echo $indice;?>]" value="<?php echo $value->id;?>"  size="2"/>
                    <input type="hidden" name="clave_id1[<?php echo $indice;?>]"  id="clave_id1[<?php echo $indice;?>]" value="<?php echo $clave_id1;?>"  size="2"/>
                    <input type="hidden" name="clave_id2[<?php echo $indice;?>]"  id="clave_id2[<?php echo $indice;?>]" value="<?php echo $clave_id2;?>"  size="2"/>
                    <?php echo $indice+1;?>
               </td>
               <td style="text-align:left;"><input type="image" name="icono_local" id="icono_local" src="/images/<?php echo $value->icono_local;?>" border="0"/><?php echo $value->local;?></td>
               <td>vs</td>
               <td style="text-align:left;"><input type="image" name="icono_visita" id="icono_visita" src="/images/<?php echo $value->icono_visita;?>" border="0"/><?php echo $value->visita;?></td>
               <td align="center"><input type="text" class="numeros" name="gol_local[<?php echo $indice;?>]" id="gol_local[<?php echo $indice;?>]" size="3"  value="<?php echo $goles_local;?>"/></td>
               <td align="center">
                    <input type="text" class="numeros" name="gol_visita[<?php echo $indice;?>]" id="gol_visita[<?php echo $indice;?>]" size="3"  value="<?php echo $goles_visita;?>"/>
                    <input type="hidden" name="situacion[<?php echo $indice;?>]" id="situacion[<?php echo $indice;?>]" size="3" value="<?php echo $value->situacion;?>">
               </td>
          </tr>
          <?php
          }
          ?>
</table>
</div>
<div style="float: left;width: 900px; margin-top: 10px;">
     <p align="center">
         <a href="/panel/resultado" class="aceptarlog2">REGRESAR</a>&nbsp;&nbsp;&nbsp;
         <a href="#" class="aceptarlog2" onclick="grabar_resultado_partido();">GRABAR</a>
     </p>
</div>
</form>