<div class="crearbanner">
<h1><?php echo $this->form_title ?></h1>
</div>

<div class="containertable">
<div class="container_bg patbotom">
<table style="width: 80%" border="0" cellspacing="0" cellpadding="5">
	<tr class="list1">
		<td rowspan="3" style="vertical-align: top; padding-top: 10px;">
			<img width="50" height="45" src="/fotos/<?php echo $this->jugador->foto; ?>" />
		</td>
		<td colspan="2" style="text-align: left; padding-left: 5px;"><?php echo $this->tipo->descripcion ?>: <?php echo $this->jugador->numero_doc ?></td>
	</tr>			
	<tr>		
		<td class="text1">Nombres:</td>
		<td><?php echo $this->jugador->nombres; ?></td>
	</tr>
	<tr class="list1">		
		<td class="text1" style="text-align: left;padding-left: 5px;">Apellidos:</td>
		<td style="text-align: left;padding-left: 5px;"><?php echo $this->jugador->apellidos; ?></td>
	</tr>
	<tr>	
		<td>&nbsp;</td>	
		<td  class="text1">Email:</td>
		<td><?php echo $this->jugador->email; ?></td>
	</tr>
	<tr class="list1">
		<td style="background: #fff;">&nbsp;</td>		
		<td class="text1" style="text-align: left;padding-left: 5px;">Tel&eacute;fono:</td>
		<td style="text-align: left;padding-left: 5px;"><?php echo $this->jugador->telefono; ?></td>
	</tr>
	<?php if($this->jugador->dni_apoderado != ""): ?>
	<tr>
		<td>&nbsp;</td>
		<td  class="text1">DNI Apoderado:</td>
		<td><?php echo $this->jugador->dni_apoderado; ?></td>
	</tr>
	<?php endif; ?>
	<tr>
		<td colspan="3" style="text-align: right; padding-top: 10px;">
			<a href="#" onclick="regresar();" id="btnRegresar" class="aceptarlog2">Regresar</a>
		</td>
	</tr>
</table>
</div>
</div>
