<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->headTitle() . "\n" ?>
<?php echo $this->headLink() . "\n" ?>
<?php echo $this->headScript() . "\n" ?>
<script type="text/javascript">
$(function (){
	// $('#body').css('text-align', 'center');
});
</script>
</head>

<body>
<div id="wrap-content">
  <div id="header">CABECERA</div>
  <div id="content"><?php echo $this->layout()->content ?></div>
  <div id="footer">PIE</div>
</div>
</body>
</html>
