<div class="pop480 popStyle">
	<h1>T&eacute;rminos y condiciones</h1>
    <p class="bold">Para completar tu registro debes leer y aceptar los t&eacute;rminos y condiciones del juego &ldquo;El Profe depor</p>
    
  <div class="terminos">
<p>Bienvenido a la web de &ldquo;EL PROFE DEPOR&rdquo;, aqu&iacute; podr&aacute;s divertirte jugando con   los resultados del Campeonato Descentralizado. El acceso o uso de esta comunidad   interactiva implica la aceptaci&oacute;n sobre la lectura, el entendimiento y el   acuerdo de las siguientes &ldquo;POL&Iacute;TICAS DEL SITIO&rdquo;. Nosotros nos reservamos el   derecho, a nuestra libre discreci&oacute;n, de cambiar, modificar, adicionar o borrar   partes de las presentes &ldquo;POLITICAS DEL SITIO&rdquo;.</p>
<h2>Periodo</h2>
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx<br />
<br />
<h2>Calificaci&oacute;n y premios</h2>
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<p><strong>&nbsp;</strong></p>
<h2>&iquest;Qui&eacute;nes pueden participar?</h2>
<ul>
  <li>Pueden participar hombres y mujeres de todas las edades que residan en   Lima-Per&uacute;.</li>
  <li>No participan en el concurso el personal y todas aquellas personas que   presenten servicios directa o indirectamente a la empresa organizadora del   concurso. </li>
  <li>Los ganadores aceptan participar de acciones promocionales que EMPRESA   EDITORA EL COMERCIO S.A. realice para difundir los resultados del concurso como   sesi&oacute;n de fotos y testimoniales, sin recibir ning&uacute;n pago a cambio. </li>
  <li>Las historias enviadas ser&aacute;n previamente aprobadas antes de ser   publicadas.</li>
</ul>
<p><strong>&nbsp;</strong></p>
<h2>Protecci&oacute;n de Datos </h2>
<p>El sitio est&aacute; protegido por una amplia variedad de medidas de seguridad,   tales como procedimientos de control de cambios y controles de acceso f&iacute;sico.   Dichos controles incluyen pol&iacute;ticas de confidencialidad y respaldo peri&oacute;dico de   bases de datos. Tambi&eacute;n empleamos otros mecanismos para asegurar que los datos   que los usuarios proporcionan no sean extraviados, mal utilizados o modificados   inapropiadamente.<strong>&nbsp;</strong></p>
<h2>Disponibilidad, utilidad y falibilidad </h2>
<p>EMPRESA EDITORA EL COMERCIO S.A. no garantiza la disponibilidad y continuidad   del funcionamiento del Sitio y de los Servicios que en este se ofrecen. Cuando   sea razonablemente posible, EMPRESA EDITORA EL COMERCIO S.A. advertir&aacute;,   previamente, las interrupciones en el funcionamiento del sitio. EMPRESA EDITORA   EL COMERCIO S.A. tampoco garantiza la utilidad del sitio ni la infalibilidad del   mismo, eximi&eacute;ndose de toda responsabilidad, de manera particular aunque no   exclusiva, ante los fallos o errores que puedan presentarse durante el proceso   de acceso a las distintas p&aacute;ginas web del sitio o a las que deriven de   estas.</p>
<h2>Contenido del sitio</h2>
<p>Quedan reservados, en los t&eacute;rminos previstos en la ley de Propiedad   Intelectual, &uml;Decreto Legislativo 822&uml;<strong>. </strong>Todo el contenido   disponible en el sitio, incluyendo dise&ntilde;os, texto, gr&aacute;ficas, cuadros, v&iacute;deo,   informaci&oacute;n, usos, software, m&uacute;sica, sonido y otros archivos, y su selecci&oacute;n y   arreglo, es propiedad exclusiva de EMPRESA EDITORA EL COMERCIO S.A. Ning&uacute;n   Contenido del site puede ser modificado, copiado, distribuido, enmarcado,   reproducido, republicado, descargado, mostrado, fijado, transmitido, o vendido   en cualquier forma o por cualquier medio, en&nbsp; todo o en parte, sin el permiso   previo escrito de la Empresa. </p>
<p>EMPRESA EDITORA EL COMERCIO S.A. se reserva el derecho de publicaci&oacute;n de   comentarios que atenten contra la moral y las buenas costumbres, o est&eacute;n   cargados de mensajes comerciales o pol&iacute;ticos.</p>
<h2>Publicidad</h2>
<p>Al aceptar este convenio, EMPRESA EDITORA EL COMERCIO S.A. podr&aacute; enviar   publicidad al correo electr&oacute;nico ingresado en el formulario de Inscripci&oacute;n.</p>
<h2>Mayor informaci&oacute;n </h2>
<p>Si tiene alguna consulta acerca de la declaraci&oacute;n de seguridad y privacidad   en cuesti&oacute;n, las pr&aacute;cticas usadas en el sitio web, o sus relaciones con nuestra   empresa, puede ponerse en contacto enviando un correo electr&oacute;nico a:   xxxxxxxxxxxxxxxxxxxxxxxxxxx</p>
</div> <!--fin terminos-->
    <form id="formConfirm" name="formConfirm" method="post" action="<?php echo $this->action_form ?>">
      <a href="javascript:;" class="btnNaranja65 bold center btnBig" id="btnConfirm">Aceptar</a>
                        </form>
</div>
