<center>
<table border="1" width="90%" cellpadding="0" cellspacing="2">
     <thead>
          <tr>
               <th>ID</th>
               <th>DESCRIPCION</th>
               <th>TIPO</th>
               <th>ACCION</th>
          </tr>
     </thead>
     <tbody>
     <?php
     foreach($this->entries as $indice => $fecha){
          $descripcion = $fecha->DESCRIPCION;
          $tipo        = $fecha->TIPO;
     ?>
          <tr>
               <td align="center"><?php echo $indice+1;?></td>
               <td align="left"><?php echo $descripcion;?></td>
               <td align="left"><?php echo $tipo;?></td>
               <td align="center"></td>
          </tr>
     <?php
     }
     ?>
     </tbody>
</table>
</center>