<table width="100%" cellspacing="0" cellpadding="3">
    <tr>
        <td>
            <form action="#" id="frmUpdateArticulo" name="frmUpdateArticulo" method="post">
                <input type="hidden" id="articulo_id" name="articulo_id" value="<?php echo $this->articulo_id; ?>" />
                <table border="0" width="100%" cellpadding="0" cellspacing="0">
                    <tbody>
                        <tr>
                            <td align="left">Tipo: </td>
                            <td align="left">
                                <select name="tipo" id="tipo" disabled="disabled">
                                    <?php foreach ($this->tarticulo as $tipo): ?>
                                    <?php if ($this->tipoarticulo_id == $tipo->tipoarticulo_id): ?>
                                            <option value="<?php echo $tipo->tipoarticulo_id ?>" selected="selected"><?php echo $tipo->nombre ?></option>
                                    <?php else: ?>
                                                <option value="<?php echo $tipo->tipoarticulo_id ?>"><?php echo $tipo->nombre ?></option>
                                    <?php endif; ?>
                                    <?php endforeach; ?>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td align="left">T&iacute;tulo: </td>
                            <td align="left">
                                <input type="text" name="titulo" id="titulo" value="<?php echo $this->titulo; ?>" size="40" maxlength="40" />
                            </td>
                        </tr>
                        <tr>
                            <td align="left">Descripcion: </td>
                            <td align="left">
                                <textarea name="descripcion" id="descripcion" cols="60" rows="4"><?php echo $this->descripcion; ?></textarea>
                            </td>
                        </tr>
                        <tr>
                            <td align="left">Contenido: </td>
                            <td align="left">
                                <label>
                                    <textarea class="tinymce" id="contenido" name="contenido">
                                        <?php echo html_entity_decode($this->contenido); ?>
                                    </textarea>
                                </label>
                            </td>
                        </tr>
                        <tr>
                            <td align="center" colspan="2">&nbsp;</td>
                        </tr>
                        <tr>
                            <td align="center">&nbsp;</td>
                            <td align="center"><a href="javascript:;" onclick="actualizar_noticia();" id="btnModificarArt" name="btnModificarArt">[Modificar]</a></td>
                        </tr>
                    </tbody>
                </table>
            </form>
        </td>
    </tr>
</table>