<div style="float: left; width: 30%">
<h2><?php echo $this->title ?></h2>
<?php echo $this->form ?>
</div>
<div style="float: left; width: 70%">
<br />
<div><a href="#" onclick="window.open('/facebook/redirect/', 'Facebook', 'menubar=no,width=790,height=360,toolbar=no');"><img src="<?php echo $this->Image('facebook_connect.gif') ?>" alt="Sign in with Facebook"/></a></div><br />
<div><a href="#" onclick="window.open('/twitter/redirect/', 'Twitter', 'menubar=no,width=790,height=360,toolbar=no');"><img src="<?php echo $this->Image('lighter.png') ?>" alt="Sign in with Twitter"/></a></div><br />
<div><a href="#" id="btnGoogle"><img src="<?php echo $this->Image('gfc_button.png') ?>" alt="Sign in with Google"/></a></div>

</div>
<div style="clear: both"></div>