<div class="pop438 popStyle olvContra">
  <h1>Contraseña</h1>
  <h3 style="margin-top: 35px;">Modifica tu contraseña</h3>
  <p style="text-align:center;">Modifica la nueva contraseña para poder ingresar a tu cuenta.</p>
  <form id="formCambiarPass" name="formCambiarPass" method="post" action="">
    <div id="form-errors"></div>
    <div style="width: 386px; text-align: center; margin: 12px auto 0; float: left;">
      <label  id="label-password">Contraseña actual:</label>
      <input name="password" class="required" type="password" id="password" />
    </div>
    <div style="width: 386px; text-align: center; margin: 12px auto 0; float: left;">
      <label  id="label-new_password">Nueva contraseña:</label>
      <input name="new_password" type="password" id="new_password" />
    </div>
    <div style="width: 386px; text-align: center; margin: 12px auto 0; float: left;">
      <label  id="label-confirm_password">Repetir contraseña:</label>
      <input name="confirm_password" type="password" id="confirm_password" />
    </div>
    <div class="clear"></div>
    <a href="#" id="submit" class="btnNaranja100 bold center btnBig">Enviar</a>
  </form>
</div>