		<div class="juegoFases juegoFixture1">

        	<div class="fasesLeft">

                <div class="faseHeadLeft">
                    <h5>Fixture y mis jugadas</h5>
                    <h6>Fecha <?php echo (int)$this->fechas['descripcion']?>. <?php echo $this->primera_fecha->fecha_partido;?></h6>
                </div> <!--fin faseHead-->

                <ul class="tableFixture">
                    <li class="head"><div class="local">Local</div><div class="visita">Visita</div></li>
                    <?php
                    foreach($this->partidos as $indice=>$value){
                         $clase = $indice%2==0?'list1':'list2';
                         ?>
                          <li class="<?php echo $clase;?>">
                             <div class="fechaTabla"><?php echo $value->fecha_partido;?></div>
                             <div class="equipo"><img class="unitPng" src="/images/<?php echo $value->icono_local;?>" /><p><?php echo $value->local;?></p></div>
                             <div class="versus unitPng"></div>
                             <div class="equipo"><img class="unitPng" src="/images/<?php echo $value->icono_visita;?>" /><p><?php echo $value->visita;?></p></div>
                         </li>
                         <?php
                         }
                         ?>
                </ul>
				<p class="bottomFixtureLeft unitPng">Puntos ganados nivel 2: <span class="bold"><?php echo $this->puntajes[0]?></span></p>

            </div> <!--fin fasesLeft-->
            <div class="fasesRight">
                <div class="faseHeadRight">
                	<a href="#" class="btnNaranja100 bold right">Cerrar</a>
                    <div class="clear"></div>
                    <div class="fixtureNiveles">
                    <a href="/fixture/nivel1/id/<?php echo $this->fechas['fecha_id'];?>">Nivel 1</a>
                    <a class="activo" href="/fixture/nivel2/id/<?php echo $this->fechas['fecha_id'];?>">Nivel 2</a>
                    <a href="/fixture/nivel3/id/<?php echo $this->fechas['fecha_id'];?>" style="border: none;">Nivel 3</a>
                    </div>
                </div> <!--fin faseHead-->

                <ul class="tablePronostico">
                    <li class="head"><div class="local">Dijiste que:</div><div class="visita">Ser&aacute; por:</div></li>
                    <?php
                    foreach($this->partidos as $indice=>$value){
                         $clase                   = $indice%2==0?'list1':'list2';
                         $intervalos        =  $value->intervalos;
                         $variable_res   = $value->variable_id;
                         $intervalo_res = $value->intervalo_id;
                         ?>
                    <li class="<?php echo $clase;?>">
                        <div class="estadon"><?php echo $value->nombre_resultado;?></div>
                        <div class="equipo"><?php if($value->icono_equipo != null):?>
                        	<img src="<?php echo $this->Image($value->icono_equipo);?>" />
                        	<p><?php echo $value->nombre_equipo;?></p>
                        	<?php else: ?>
                        	<p>&nbsp;</p>
                        	<p>&nbsp;</p>
                        	<?php endif; ?>
                        </div>
                        <?php
                        switch($variable_res){
                             case 5:
                                   $style = $value->nombre_resultado==""?"style='display:none;'":"";
                                    ?> 
                                    <div class="opt1" <?php echo $style;?>><input name="intervalos[<?php echo '5';?>][<?php echo '5';?>]" id="intervalos[<?php echo "5";?>][<?php echo "5";?>]" type="checkbox" value="" /><p>&nbsp;</p></div>
                                   <div class="opt2" <?php echo $style;?>><input name="intervalos[<?php echo '5';?>][<?php echo '5';?>]" id="intervalos[<?php echo "5";?>][<?php echo "5";?>]" type="checkbox" value="" /><p>&nbsp;</p></div>
                                    <?php
                                    break;
                               case 6:
                                    ?>
                                   <div class="opt1"><input name="intervalos[6][6]" id="intervalos[<?php echo '6';?>][<?php echo '6';?>]" type="checkbox" value="" <?php echo $intervalo_res=='6'?"checked='checked'":"";?>/><p><?php echo $intervalos[0]['descripcion'];?> (<?php echo $intervalos[0]['puntaje'];?>pts.)</p></div>
                                   <div class="opt2"><input name="intervalos[6][7]" id="intervalos[<?php echo '6';?>][<?php echo '7';?>]" type="checkbox" value="" <?php echo $intervalo_res=='7'?"checked='checked'":"";?>/><p><?php echo $intervalos[1]['descripcion'];?> (<?php echo $intervalos[1]['puntaje'];?>pts.)</p></div>
                                    <?php
                                    break;
                               case 7:
                                    ?>
                                   <div class="opt1"><input name="intervalos[7][8]" id="intervalos[<?php echo '7';?>][<?php echo '8';?>]"  type="checkbox" value="" <?php echo $intervalo_res=='8'?"checked='checked'":"";?>/><p><?php echo $intervalos[0]['descripcion'];?> (<?php echo $intervalos[0]['puntaje'];?>pts.)</p></div>
                                   <div class="opt2"><input name="intervalos[7][9]" id="intervalos[<?php echo '7';?>][<?php echo '9';?>]" type="checkbox" value="" <?php echo $intervalo_res=='9'?"checked='checked'":"";?>/><p><?php echo $intervalos[1]['descripcion'];?> (<?php echo $intervalos[1]['puntaje'];?>pts.)</p></div>
                                    <?php
                                    break;
                               case 8:
                                    ?>
                                   <div class="opt1"><input name="intervalos[8][10]" id="intervalos[<?php echo '8';?>][<?php echo '10';?>]"  type="checkbox" value="" <?php echo $intervalo_res=='10'?"checked='checked'":"";?>/><p><?php echo $intervalos[0]['descripcion'];?> (<?php echo $intervalos[0]['puntaje'];?>pts.)</p></div>
                                   <div class="opt2"><input name="intervalos[8][11]" id="intervalos[<?php echo '8';?>][<?php echo '11';?>]" type="checkbox" value="" <?php echo $intervalo_res=='11'?"checked='checked'":"";?>/><p><?php echo $intervalos[1]['descripcion'];?> (<?php echo $intervalos[1]['puntaje'];?>pts.)</p></div>
                                    <?php
                                    break;
                         }
                        ?>
                    </li>
                  <?php
                    }
                  ?>
                </ul>

				<p class="bottomFixtureRight unitPng">Puntos totales de la fecha: <span class="bold"><?php echo $this->puntajes[1]?></span></p>


            </div> <!--fin fasesRight-->

		</div> <!--fin juegoFases-->